LogisticRegression:
  classifier__C: [100, 1000, 10000]
  classifier__solver: ["lbfgs", "liblinear"]
  feature_selection__k: [8, "all"]
  classifier__class_weight: ["balanced"]

RandomForest:
  classifier__n_estimators: [50, 75]
  classifier__max_depth: [20, 25]
  classifier__min_samples_split: [4, 5]
  classifier__min_samples_leaf: [2, 3]
  feature_selection__k: [10, "all"]
  classifier__class_weight: ["balanced"]

XGBClassifier:
  classifier__n_estimators: [500, 700]
  classifier__max_depth: [3, 4]
  classifier__learning_rate: [0.05, 0.07]
  classifier__subsample: [0.7, 0.9]
  classifier__colsample_bytree: [0.6, 0.7]
  classifier__min_child_weight: [0.5, 1]
  classifier__gamma: [0, 1]
  classifier__scale_pos_weight: [80, 100, 120]

