XGBClassifier:
  classifier__subsample: [0.7]
  classifier__scale_pos_weight: [773]
  classifier__n_estimators: [500]
  classifier__min_child_weight: [1]
  classifier__max_depth: [3]
  classifier__learning_rate: [0.05]
  classifier__gamma: [1]
  classifier__colsample_bytree: [0.6]

