[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fraud_detection"
version = "0.0.1"
description = "Projeto de detecção de fraude"
readme = "README.md"
authors = [{name="Eduardo"}]
# Não precisa listar dependências aqui se preferir usar requirements.txt
# dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
